songwriting:
  description: >
    Write a song about giving 100% of your focus to improving the quality of your life through small daily improvements
  expected_output: >
    Output a song with lyrics and melody.
  agent: songwriter 

producing:
  description: >
    Output the chord progression and melody for the song so that the artist and engineer can record, program, and mix that song
  expected_output: >
    The lyrics, melody, and chord progression for the song clearly and simply outlined
  agent: producer
